### ISSUE TITLE
What were your findings?

### ISSUE THREAD

**Issue by derek-adair** [sephii/mezzanine-grappelli#5]
I have been wanting to use the new grapelli for some time now... and i stumbled across this.  

 What were the reasons these efforts were abandoned?

**Comment by sephii** [comment]
The reason is just that I don't use Mezzanine anymore. As for the reason this didn't get merged in Mezzanine, please refer to https://github.com/stephenmcd/mezzanine/pull/912.

Anyway, feel free to fork this repo and update the code. I'd be happy to redirect people to an up-to-date version.

**Comment by derek-adair** [comment]
Is there any reason in particular you dont use Mezzanine anylonger?  What do you use now?  I've implemented some pretty simple projects that are starting to mature so its sortof time to fully embrace Mezzanine, fork this project or just move on.

**Comment by sephii** [comment]
I'm using DjangoCMS now mainly because of its nicer looking interface and its bigger community. Give it a try and then decide whether you want to stick with Mezzanine or go with DjangoCMS.

**Comment by derek-adair** [comment]
Damn i feel dumb now for not having seen this project.

Cheers.
